from collections.abc import Iterator
from typing import Protocol

import numpy as np

type Vector[T: np.generic = np.floating] = np.ndarray[tuple[int], np.dtype[T]]
type Matrix[T: np.generic = np.floating] = np.ndarray[tuple[int, int], np.dtype[T]]
type MatrixStack[T: np.generic = np.floating] = np.ndarray[tuple[int, int, int], np.dtype[T]]

class VectorLike[T](Protocol):
    """See `numpy._typing._nested_sequence._NestedSequence`."""
    def __len__(self, /) -> int: ...
    def __getitem__(self, index: int, /) -> T: ...
    def __contains__(self, x: object, /) -> bool: ...
    def __iter__(self, /) -> Iterator[T]: ...
    def __reversed__(self, /) -> Iterator[T]: ...
    def count(self, value: T, /) -> int: ...
    def index(self, value: T, /) -> int: ...

type SingleIndex = int | np.intp
type IndexVector = VectorLike[int] | Vector[np.intp]
